# Generated by Django 5.1.4 on 2024-12-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
